server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  # Proxy API requests to user-service container
  location /api/ {
    proxy_pass http://user-service:8080/api/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }

  # Proxy documents API requests to documents-service container
  location = /api/documents {
    return 301 /api/documents/;
  }
  location /api/documents/ {
    proxy_pass http://documents-service:8084/api/documents/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }

  # Proxy billing API requests to billing-service container
  location = /api/billing {
    return 301 /api/billing/;
  }
  location /api/billing/ {
    proxy_pass http://billing-service:8085/api/payments/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }

  # Proxy practitioner API requests to practitioner-service container
  location /api/practitioner/ {
    proxy_pass http://practitioner-service:8081/api/practitioner/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }

  # Proxy patient API requests to patient-service container
  location /api/patient/ {
    proxy_pass http://patient-service:8082/api/patient/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }

  # Proxy appointment API requests to appointment-service container
  location /api/appointment/ {
    proxy_pass http://appointment-service:8087/api/appointment/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }

  # Proxy medical catalog API requests to medical-catalog-service container
  location /api/catalog/ {
    proxy_pass http://medical-catalog-service:8083/api/catalog/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
}
