#!/bin/sh
exit 1
set -e
echo "Husky pre-commit hook running on branch: $(git rev-parse --abbrev-ref HEAD)"
branchName=$(git rev-parse --abbrev-ref HEAD)
if [ "$branchName" = "main-v2" ]; then
  echo "Cannot commit directly to 'main-v2'. Use a feature branch."
  exit 1
fi
npx lint-staged