using './billingservice.module.bicep'

param azurecorsallowedorigins_value = '{{ parameter "azurecorsallowedorigins" }}'
param azurejwtsecret_value = '{{ securedParameter "azurejwtsecret" }}'
param azurerabbitmqpassword_value = '{{ securedParameter "azurerabbitmqpassword" }}'
param azurewebhookssecretmock_value = '{{ securedParameter "azurewebhookssecretmock" }}'
param azurewebhookssecretstripe_value = '{{ securedParameter "azurewebhookssecretstripe" }}'
param billingservice_containerimage = '{{ .Image }}'
param billingservice_containerport = '{{ targetPortOrDefault 8080 }}'
param outputs_azure_container_apps_environment_id = '{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}'
param outputs_azure_container_registry_endpoint = '{{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}'
param outputs_azure_container_registry_managed_identity_id = '{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}'
param outputs_managed_identity_client_id = '{{ .Env.MANAGED_IDENTITY_CLIENT_ID }}'
param sql_outputs_sqlserverfqdn = '{{ .Env.SQL_SQLSERVERFQDN }}'
