// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService.Data;

#nullable disable

namespace NotificationService.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    [Migration("20251229190608_GuidRefactor")]
    partial class GuidRefactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notifications")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotificationService.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Action_Url")
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Creation_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("Expires_At")
                        .HasColumnType("datetime");

                    b.Property<bool?>("Is_Read")
                        .HasColumnType("bit");

                    b.Property<string>("Priority_Level")
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("Recipient_User_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source_Service")
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Notification", "notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
